### ISSUE TITLE
mp4v2 bug in 0.25

### ISSUE THREAD

**Issue by pdr0github** [nu774/mp4fpsmod#22]
mp4v2 files have corrupt playback in various media players (vlc, mpchc, potplayer etc...) with mp4fpsmod 0.25, but work ok with 0.24 . mp4v1 seems ok too in either

Background context is "fixing" VFR jitter from samples cut from avidemux . Original was CFR

> Frame rate mode                          : Variable
> Frame rate                               : 23.976 (23976/1000) FPS
> Minimum frame rate                       : 23.000 FPS
> Maximum frame rate                       : 23.981 FPS

Sample cut ~8.5Mb from YT trailer, in avidemux as mp4v2 output to reproduce issue
https://www.mediafire.com/file/e33mqr6rzse49oe/cut_mp4v2.mp4/file

command lines used
"D:\Utilities\mp4fpsmod_0.25\mp4fpsmod" --fps 0:24000/1001 cut_mp4v2.mp4 -o mp4fpsmod0.25.mp4
"D:\Utilities\mp4fpsmod_0.24\mp4fpsmod" --fps 0:24000/1001 cut_mp4v2.mp4 -o mp4fpsmod0.24.mp4

**Comment by nu774** [comment]
Thanks. It turned out that v0.25 could not read co64 box correctly.
Fixed in v0.26 now.
