### ISSUE TITLE
Cannot edit timestamp of first frame from timecode-v2 file

### ISSUE THREAD

**Issue by ieno98** [nu774/mp4fpsmod#33]
I'm using mp4fpsmod because I cannot find the ability to change mdhd/Timescale in timelineeditor of the L-SMASH Project, but when I edit MP4 timestamp using mp4fpsmod's -t option, the timestamp of the first frame is not reflected in the output, although L-SMASH's timelineeditor can edit the timestamp of the first frame.

**Comment by nu774** [comment]
If you want non-zero timestamp for first frame, I think you can remux the resulting file by ffmpeg with -itsoffset specified.

**Comment by ieno98** [comment]
indeed, that solves the problem I'm having, so I'll take that FFmpeg in conjunction approach. Thanks.
